#1A4D9B
name: medxpress
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  palette_generator: ^0.3.0
  google_maps_flutter: ^2.5.0
  http: 1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_calendar_carousel: ^2.4.1
  provider: ^6.0.5
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Declare assets
  assets:
    - assets/images/doktor_korisnik.png
    - assets/images/doktor_medicinska_sestra_profil.png
    - assets/images/kalendar_opcenito.png
    - assets/images/korisnik_profil.png
    - assets/images/medicinska_sestra_korisnik.png
    - assets/images/pretrazivanje_doktora_opcenito.png
    - assets/images/razgovori_doktor_medicinska_sestra.png