#1A4D9B
name: medxpress
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  palette_generator: ^0.3.0
  google_maps_flutter: ^2.5.0
  http: 1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Declare assets
  assets:
    - assets/images/simptomi.jpg
    - assets/images/kalendar.jpg
    - assets/images/doctor.jpg
